//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_linq_parte_1_crie_queries_poderosas_em_c_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemNotaFiscal
    {
        public int ItemNotaFiscalId { get; set; }
        public int NotaFiscalId { get; set; }
        public int FaixaId { get; set; }
        public decimal PrecoUnitario { get; set; }
        public int Quantidade { get; set; }
    
        public virtual Faixa Faixa { get; set; }
        public virtual NotaFiscal NotaFiscal { get; set; }
    }
}
